### ISSUE TITLE
Error upgrading parity data: CannotCreateConfigPath

### ISSUE THREAD

**Issue by jwasinger** [paritytech/parity-deploy#75]
Here's what I did:
```
 ./parity-deploy.sh --config aura
docker-compose up
```

Here's what I see:
```
Attaching to host1
host1    | Loading config file from /parity/authority.toml
host1    | Error upgrading parity data: CannotCreateConfigPath
host1 exited with code 1
```

I'm running everything as root user on a VM.

**Comment by jwasinger** [comment]
Here's how I got around this:

- Start up `docker-compose up`, get error
- Do a dirty hack to make the mounted volumes writeable from within the client containers `chmod a+rwx -R deployment/ data`

Another detail:
I'm running these containers on a Virtualbox VM hosted on a windows 10 host.

What environment is parity deploy known to work in without these volume permission errors?

**Comment by ddorgan** [comment]
@jwasinger I normally run them on VM's directly and don't see these issues. Is your user a member of the docker group? e.g. can you run ```docker run myimage``` without sudo?

**Comment by bilonic** [comment]
This error happens on parity v2.0.7 and later.
With parity v2.0.6 and lower works fine.

**Comment by ddorgan** [comment]
@bilonic thanks for that, let me check this.

**Comment by branciard** [comment]
It is linked to this change in the last release :
"Docker: run parity as normal user"
 https://github.com/paritytech/parity-ethereum/pull/9689  

When volumes are mount like this
   - ./data/1:/parity/data

This will be created as root and parity user cannot write/access it.

The solution proposed in  https://github.com/paritytech/parity-ethereum/pull/9689   is to create 

`RUN mkdir -p /home/parity/.local/share/io.parity.ethereum/`
in the dockerfile

But in our case we will not be able to use -d /parity/data anymore ...

**Comment by ddorgan** [comment]
@branciard please checkout the latest master and try again. Merged a pull request: https://github.com/paritytech/parity-deploy/pull/77 to fix.

**Comment by ddorgan** [comment]
@branciard any update on this...Or will I just close the issue?

**Comment by branciard** [comment]
Yes perfect @ddorgan. I just test and it is ok with the parity user added to docker-compose and new folders targeted. Thanks !

**Comment by ddorgan** [comment]
Great thanks for the reply.

**Comment by armanfatahi** [comment]
This was because of lack of permissions on the volumes. Just notice that the volume might have been created using root user.

host1    | Error upgrading parity data: CannotCreateConfigPath

**Comment by ddorgan** [comment]
@armanfatahi yip, fixed in the latest master (when creating from scratch) or do a one time chown for existing setups.

**Comment by daithi-coombes** [comment]
Issue still persists on `stable` and `nightly`. I had to change the user to `root` to get it working

```yaml
version: "3"

services:
  parity:
    image: parity/parity:nightly
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
      - 30303:30303/udp
    user: root
    volumes:
      - ./io.parity.ethereum:/root/.local/share/io.parity.ethereum
    command: --light --jsonrpc-apis 'web3,eth,pubsub,net,parity,parity_pubsub,traces,rpc,secretstore,shh,shh_pubsub' --jsonrpc-interface 0.0.0.0 --jsonrpc-hosts="all"
```

**Comment by skinderis** [comment]
@daithi-coombes thanks, your solution solved the problem
